In [35]:
# Import Dependencies
%matplotlib inline 
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np

In [36]:
path = "IMDB Movies 2000 - 2020_clean_Jas.csv"

all_data = pd.read_csv(path)

all_data.head()

,original_title,year,genre,duration,country,language_1,director,writer,actors,actors_1,actors_f2,description,desc35,avg_vote,votes,budget,usa_gross_income,USA Profit
0,Kate & Leopold,2001,"Comedy, Fantasy, Romance",118,USA,English,James Mangold,"Steven Rogers, James Mangold","Meg Ryan, Hugh Jackman, Liev Schreiber, Brecki...",Meg Ryan,"Meg Ryan, Hugh Jackman",An English Duke from 1876 is inadvertedly drag...,An English Duke from 1876 is inadvertedly,6.4,77852,48000000,47121859,-878141
1,Glitter,2001,"Drama, Music, Romance",104,USA,English,Vondie Curtis-Hall,"Cheryl L. West, Kate Lanier","Mariah Carey, Max Beesley, Da Brat, Tia Texada...",Mariah Carey,"Mariah Carey, Max Beesley",A young singer dates a disc jockey who helps h...,A young singer dates a disc jockey,2.2,21298,22000000,4274407,-17725593
2,Chicken Run,2000,"Animation, Adventure, Comedy",84,"UK, USA, France",English,"Peter Lord, Nick Park","Peter Lord, Nick Park","Phil Daniels, Lynn Ferguson, Mel Gibson, Tony ...",Phil Daniels,"Phil Daniels, Lynn Ferguson",When a cockerel apparently flies into a chicke...,When a cockerel apparently flies,7.0,173987,45000000,106834564,61834564
3,Fantastic Four,2005,"Action, Adventure, Fantasy",106,"USA, Germany",English,Tim Story,"Mark Frost, Michael France","Ioan Gruffudd, Jessica Alba, Chris Evans, Mich...",Ioan Gruffudd,"Ioan Gruffudd, Jessica Alba",A group of astronauts gain superpowers after a...,A group of astronauts gain superpowers,5.7,307944,100000000,154696080,54696080
4,Frida,2002,"Biography, Drama, Romance",123,"Mexico, USA, Canada",English,Julie Taymor,"Hayden Herrera, Clancy Sigal","Salma Hayek, Mía Maestro, Amelia Zapata, Aleja...",Salma Hayek,"Salma Hayek, Mía Maestro","A biography of artist Frida Kahlo, who channel...","A biography of artist Frida Kahlo,",7.4,79690,12000000,25885000,13885000